### ISSUE TITLE
receive 500 when simulate /story/finishUserStoryMain

### ISSUE THREAD

**Issue by EtherealAO** [Francesco149/reversing-sifas#1]
i'm trying to make an automatic tool for reset marathon following here, written in C#. i succeed simulate startup, login and setprofiles, but after set birthday, the finishUserStoryMain request always return 500.
i used a fixed assets_state and set device_token from a real phone(and have tried to set to null). i'm sure hash algorithm is correct.
i haven't tried replace hooked asset_state with generated one,because i can't understand kotlin code and it will take serveral days to translate it into C# code.
do you have any suggestions?

**Comment by Francesco149** [comment]
error 500 probably means incorrectly formatted request. 403 is usually for incorrect session key

I have just implemented this api call in https://github.com/Francesco149/todokete with no issues. I would check the order of your url parameters as well as request format.

**Comment by EtherealAO** [comment]
From game: POST /ep1010/story/finishUserStoryMain?p=a&mv=678fe398adca191d&id=8&u=663032738&t=1572067454788 HTTP/1.1
[{"cell_id":1001,"is_auto_mode":false},"5264d9598d6a6060a26c7f0272a4a08b9bc2f8d2"]
From tool: POST /ep1010/story/finishUserStoryMain?p=a&mv=678fe398adca191d&id=10&u=686578145&t=1572073140343 HTTP/1.1
[{"cell_id":1001,"is_auto_mode":false},"1592cfcc405d08557efbb237fc734464b60c92c6"]
(retried for several times so id is also be increased)
only the order of headers is different, and even i use fiddler to compose a request with same order, still receive 500
I've been stuck here for three days :(

**Comment by Francesco149** [comment]
maybe you're sending requests too fast and the server is checking timing? try adding random sleeps like mine

**Comment by EtherealAO** [comment]
already tried,random sleeps from 1minute to 3minutes.
and i deleted randomDelay() , it still works. so server seems doesn't check timings

**Comment by EtherealAO** [comment]
fixed. i send setProfileBirthday to an error address. haha
but anyway thanks for your help and blog
